### ISSUE TITLE
No CRD's are Installed

### ISSUE THREAD

**Issue by ikegentz** [cert-manager/cert-manager-olm#102]
I am attempting to install the operator with a subscription:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: operators
spec:
  channel: stable
  name: cert-manager
  source: operatorhubio-catalog
  sourceNamespace: operators
```

While this does create an operator:

```
k get operators -n operators

NAME                        AGE
cert-manager.operators      28m
```

Nothing comes of it. No CRD's get installed, and there are no events or any indication of the operator actually trying to create anything.
